fix code symlink

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -169,7 +169,7 @@ then
 fi
 
 echo ''
-info "starting jldeen mods"
+info "starting mdavis mods"
 #backup old bin, if exists
 if [ -d $HOME/bin ]
 then
@@ -187,9 +187,11 @@ ln -s $HOME/.dotfiles/bin $HOME/bin && success "symlink for $HOME/bin folder cre
 ln -s $HOME/.dotfiles/tmux $HOME/.tmux && success "symlink for $HOME/.tmux folder created"
 
 # symlink VSCode User Settings
-if [ -d $HOME/Library/Application\ Support/Code/User ] ; then 
-  ln -s $HOME/.dotfiles/code/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
-  success "symlink for vs code settings created"
+if [ -d $HOME/Library/Application\ Support/Code/User ] ; then
+  echo "Making backup of current settings.json and creating symlink..."
+  echo ''
+  mv $HOME/Library/Application\ Support/Code/User/settings.json $HOME/Library/Application\ Support/Code/User/settings.old.json && success "settings.old.json created"
+  ln -s $HOME/.dotfiles/code/settings.json $HOME/Library/Application\ Support/Code/User/settings.json && success "settings.json for vs code symlink created"
 else
   info "symlink for vs code settings not created"
   echo "VS Code does not appear to be installed or has not been launched yet. Cannot create symlink for VS Code User settings..."
@@ -213,41 +215,41 @@ if ! [ -f /usr/local/bin/airport ]
   fi
 
 # crontab additions
-add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
-  if [[ $? -eq 0 ]]
-  then
-  success "$PATH added to crontab"
-  else
-  info "ERROR $PATH could not be added to crontab"
-  fi
+# add_line "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+#   if [[ $? -eq 0 ]]
+#   then
+#   success "$PATH added to crontab"
+#   else
+#   info "ERROR $PATH could not be added to crontab"
+#   fi
 
-add_cron "speedtest-cli --simple > ~/bin/bandwidth.log"
-  if [[ $? -eq 0 ]]
-  then
-  success "crontab created for speedtest cli --simple"
-  else
-  info "ERROR crontab could not be created for speedtest cli --simple"
-  fi
+# add_cron "speedtest-cli --simple > ~/bin/bandwidth.log"
+#   if [[ $? -eq 0 ]]
+#   then
+#   success "crontab created for speedtest cli --simple"
+#   else
+#   info "ERROR crontab could not be created for speedtest cli --simple"
+#   fi
 
-add_cron "speedtest-cli --json > ~/bin/bandwidth.json"
-  if [[ $? -eq 0 ]]
-  then
-  success "crontab created for speedtest cli --json"
-  else
-  info "ERROR crontab could not be created for speedtest cli --json"
-  fi
+# add_cron "speedtest-cli --json > ~/bin/bandwidth.json"
+#   if [[ $? -eq 0 ]]
+#   then
+#   success "crontab created for speedtest cli --json"
+#   else
+#   info "ERROR crontab could not be created for speedtest cli --json"
+#   fi
 
-# first run of speedtest-cli
-echo "Running speedtest-cli for tmux status bar data now..."
-speedtest-cli --simple > ~/bin/bandwidth.log
-success "speedtest-cli bandwidth.log created"
+# # first run of speedtest-cli
+# echo "Running speedtest-cli for tmux status bar data now..."
+# speedtest-cli --simple > ~/bin/bandwidth.log
+# success "speedtest-cli bandwidth.log created"
 
-speedtest-cli --json > ~/bin/bandwidth.json
-success "speedtest-cli bandwidth.json created"
+# speedtest-cli --json > ~/bin/bandwidth.json
+# success "speedtest-cli bandwidth.json created"
 
 # iterm2 config
 echo ''
-read -p "Do you currently use iTerm2 and would you like to set jldeen's custom colors? y/n" -n 1 -r
+read -p "Do you currently use iTerm2 and would you like to set mdavis's custom colors? y/n" -n 1 -r
 echo ''
 if [[ $REPLY =~ ^[Yy]$ ]]
 then
@@ -257,13 +259,13 @@ then
   defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
     if [[ $? -eq 0 ]]
     then
-        success "successfully configured iTerm2 to use jldeen's custom colors..."
+        success "successfully configured iTerm2 to use mdavis's custom colors..."
     else
-        fail "failed to apply jldeen's custom colors..." >&2
+        fail "failed to apply mdavis's custom colors..." >&2
 fi
 else 
-    echo "You chose not to use iTerm2 or jldeen's custom colors."
+    echo "You chose not to use iTerm2 or mdavis's custom colors."
 fi
 
 echo ''
-echo '	Badass macOS terminal installed!'
+echo '	Bad mamma jamma macOS terminal installed!'
